<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class HomePage extends CI_Controller {

	public function index()
	{
        //NAMBAH NUM OF REVIEW
        $data['hotPlaces'] = $this->db->query("select TITLE,PLACES.IMAGE,OPERATIONAL_TIME,HASH_TAG,FEATURED_ITEM,DISPLAY_NAME,PLACES.ID_PLACE,ADDRESS,(SELECT CEIL(AVG(RATE)) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) AS HIT from PLACES, USERS where TYPE = 'TOURISM' AND PLACES.AUTHOR = USERS.USERNAME AND (SELECT CEIL(AVG(RATE)) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) >= 4 AND (SELECT COUNT(*) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) >= 5  AND ROWNUM <= 6 AND VISIBILITY=1 ORDER BY CREATED_AT DESC")->result();
        $data['newPlaces'] = $this->db->query("select TITLE,PLACES.IMAGE,OPERATIONAL_TIME,HASH_TAG,FEATURED_ITEM,DISPLAY_NAME,PLACES.ID_PLACE,ADDRESS,(SELECT CEIL(AVG(RATE)) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) AS HIT from PLACES, USERS where TYPE = 'TOURISM' AND PLACES.AUTHOR = USERS.USERNAME AND CREATED_AT > SYSDATE-10 AND VISIBILITY=1")->result();

        $data['hotMarkets'] = $this->db->query("select TITLE,PLACES.IMAGE,OPERATIONAL_TIME,HASH_TAG,FEATURED_ITEM,AVERAGE_PRICE,DISPLAY_NAME,PLACES.ID_PLACE,ADDRESS,(SELECT AVG(RATE) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) AS HIT from PLACES, USERS where TYPE = 'MARKETS' AND PLACES.AUTHOR = USERS.USERNAME AND (SELECT AVG(RATE) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) >= 4 AND (SELECT COUNT(*) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) >= 5 AND ROWNUM <= 6 AND VISIBILITY=1 ORDER BY CREATED_AT DESC")->result();
        $data['newMarkets'] = $this->db->query("select TITLE,PLACES.IMAGE,OPERATIONAL_TIME,HASH_TAG,FEATURED_ITEM,AVERAGE_PRICE,DISPLAY_NAME,PLACES.ID_PLACE,ADDRESS,(SELECT AVG(RATE) FROM PLACE_REVIEWS WHERE ID_PLACE = PLACES.ID_PLACE) AS HIT from PLACES, USERS where TYPE = 'MARKETS' AND PLACES.AUTHOR = USERS.USERNAME AND CREATED_AT > SYSDATE-10 AND VISIBILITY=1")->result();

        if ($this->session->has_userdata('username')){
            $username = $this->session->userdata('username');
            $data['user'] = $this->usermodel->get($username);
            $this->load->view('home_page',$data);
        }
        else{
            $this->load->view('home_page',$data);
        }
	}
}